### ISSUE TITLE
It should be rewrite.

### ISSUE THREAD

**Issue by RyanKung** [alphapigger/igetui#4]
It should be rewrite

[https://github.com/kirk91/igetui/blob/master/igetui/igt_message.py#L14](url)

The ugly Java-style Python code, Just like a bullshit.

**Comment by kirk91** [comment]
Yep, it's ugly. Theses codes are from `python sdk`which in the website of getui.  It's code-style violate the rules of python, like pep8.  I also want to refactor that, but i have no time theses days. If you could enhance it, i will appreciate 😊

**Comment by kirk91** [comment]
In the next days, i will refactor it.
